spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/swp1

# Flowable configuration (using H2 for engine state)
spring.datasource.url=jdbc:h2:file:./flowable-db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
groq.api.key=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


# Flowable Async Executor
flowable.async-executor-activate=true
